"use client";

import Link from "next/link";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

export default function TermsContent() {
  const heroRef = useScrollReveal<HTMLDivElement>();
  const contentRef = useScrollReveal<HTMLDivElement>();

  return (
    <>
      {/* Hero */}
      <section className="relative h-[50vh] min-h-[400px] flex items-end overflow-hidden">
        <div
          role="img"
          aria-label="Sigiriya Rock Fortress, Sri Lanka"
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: "url('/images/public-sigiriya.webp')" }}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-background via-background/40 to-transparent" />
        <div ref={heroRef} className="reveal relative z-10 w-full px-6 sm:px-8 md:px-24 lg:px-32 max-w-[1440px] mx-auto pb-16">
          <span className="inline-block bg-primary text-on-primary text-[10px] font-bold tracking-widest uppercase px-3 py-1 rounded-full mb-4">
            Legal
          </span>
          <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-6xl text-on-surface mb-4 max-w-3xl">
            Terms of Service
          </h1>
          <p className="text-lg text-on-surface/60 max-w-2xl">
            Please read these terms carefully before booking with Helanka Vacations.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-20">
        <div ref={contentRef} className="reveal max-w-[1440px] mx-auto px-6 sm:px-8 md:px-24 lg:px-32">
          <div className="max-w-3xl space-y-12">
            <p className="text-sm text-on-surface-muted">Last updated: June 2026</p>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">1. About Us</h2>
              <p className="text-on-surface/70 leading-relaxed">
                Helanka Vacations (Pvt) Ltd is a licensed tour operator registered in Sri Lanka under the Sri Lanka Tourism Development Authority (SLTDA). We act as an intermediary between travelers and local service providers including hotels, transport operators, and activity providers. While we carefully select and monitor our partners, we are not directly liable for services rendered by third-party providers.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">2. Booking &amp; Confirmation</h2>
              <p className="text-on-surface/70 leading-relaxed">
                Bookings can be made through our website, via email, or through WhatsApp. A booking is confirmed only after we issue a quote and you accept it, and we receive the required deposit payment. Deposit amounts are specified in your personalized quote and are typically 30% of the total trip cost.
              </p>
              <p className="text-on-surface/70 leading-relaxed">
                We recommend booking at least 30 days in advance. Late bookings are subject to availability and may incur additional charges.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">3. Payment</h2>
              <p className="text-on-surface/70 leading-relaxed">
                All prices are quoted in US Dollars (USD) unless otherwise stated. Payments are accepted via bank transfer or through secure payment links generated by our finance team in coordination with Sampath Bank. The remaining balance is due prior to your arrival date as specified in your booking confirmation.
              </p>
              <p className="text-on-surface/70 leading-relaxed">
                Bank transfer details will be provided in your booking confirmation. Payments must be received at least 14 days before the travel date. Please contact us at{" "}
                <a href="mailto:info@helanka.co" className="text-primary underline hover:text-primary/80 transition-colors">
                  info@helanka.co
                </a>{" "}if you need assistance with payment arrangements.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">4. Cancellation Policy</h2>
              <p className="text-on-surface/70 leading-relaxed">
                For full details on cancellations, refunds, and no-show policies, please see our{" "}
                <Link href="/cancellation-policy" className="text-primary underline hover:text-primary/80 transition-colors">
                  Cancellation Policy
                </Link>.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">5. Travel Documentation</h2>
              <p className="text-on-surface/70 leading-relaxed">
                It is your responsibility to ensure that you hold a valid passport (with at least 6 months validity from the date of entry) and any required visas for Sri Lanka. Helanka Vacations is not liable for any issues arising from inadequate travel documentation.
              </p>
              <p className="text-on-surface/70 leading-relaxed">
                We recommend that you check the latest entry requirements with your local embassy or the Sri Lanka Department of Immigration &amp; Emigration before traveling.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">6. Travel Insurance</h2>
              <p className="text-on-surface/70 leading-relaxed">
                We strongly recommend purchasing comprehensive travel insurance before your trip. Your policy should cover medical expenses, trip cancellation, lost luggage, and personal liability. Helanka Vacations does not provide travel insurance and is not responsible for any losses not covered by your insurance.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">7. Liability</h2>
              <p className="text-on-surface/70 leading-relaxed">
                Helanka Vacations shall not be liable for any injury, damage, loss, delay, or irregularity arising from acts of God, force majeure, war, civil unrest, natural disasters, pandemics, government actions, weather conditions, or any other events beyond our reasonable control.
              </p>
              <p className="text-on-surface/70 leading-relaxed">
                Our liability for any claim is limited to the total cost of services booked through us. We are not liable for consequential, indirect, or special damages.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">8. Price Revisions</h2>
              <p className="text-on-surface/70 leading-relaxed">
                Prices are subject to change due to fluctuations in exchange rates, fuel surcharges, or government-imposed taxes and levies. Once a quote is accepted and the deposit paid, we will absorb price increases up to 2% of the quoted total. Increases beyond 2% will be communicated to you before any additional charges are applied, and you will have the option to cancel for a full refund.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">9. Changes to Your Booking</h2>
              <p className="text-on-surface/70 leading-relaxed">
                If you wish to modify your booking after confirmation, please contact us as soon as possible. We will do our best to accommodate changes, but they are subject to availability and may incur additional costs. Changes requested within 14 days of travel may not be possible.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">10. Governing Law</h2>
              <p className="text-on-surface/70 leading-relaxed">
                These terms are governed by the laws of Sri Lanka. Any disputes arising from or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of Sri Lanka.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="font-[family-name:var(--font-display)] text-2xl text-on-surface">11. Contact</h2>
              <p className="text-on-surface/70 leading-relaxed">
                If you have questions about these terms, please contact us at{" "}
                <a href="mailto:info@helanka.co" className="text-primary underline hover:text-primary/80 transition-colors">
                  info@helanka.co
                </a>.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
